apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec: # deployment
  replicas: 1
  selector: # selector utilizado para criar service
    matchLabels:
      app: mysql-server
      tier: db
  template: #ref pods
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: # ref container
      containers:
        - image: mysql:5.7
          name: mysql-server
          args:
            - "--ignore-db-dir=lost+found"

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password

          ports:
            - containerPort: 3306

          volumeMounts: # monta o volume efetivamente
            - name: mysql-persistent-volume
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim
